### ISSUE TITLE
Fix preview builds on PRs

### ISSUE THREAD

**Issue by kescobo** [kescobo/blog.bonham.ch#4]
@tlienart Another thing to check (if you like) - I tried modifying the build workflow from the Xranklin repo, and it works for the main build, but PR doesn't. See eg https://github.com/kescobo/blog.bonham.ch/actions/runs/5717835707/job/15492370111 from #2 . The PR preview build failed, but when I merged to main, it built fine

**Comment by tlienart** [comment]
🤔 this is a bit of a weird one, especially when the same operation worked for everything else but that post; I'll investigate.

**Comment by kescobo** [comment]
fixed in #7
