### ISSUE TITLE
using pages of yours to speed up FranklinParser TTFX

### ISSUE THREAD

**Issue by tlienart** [kescobo/blog.bonham.ch#5]
down the rabbit hole of figuring out where performances might be improved, I played a bit with PrecompileTools and pages of yours, this basically lead to a halving of the corresponding TTFX which is very nice (from ~0.9ms for the page to ~0.5ms). There are other bottlenecks but I thought it was quite nice so wanted to put it in anyway.

Do you mind if FranklinParser is packaged with a precompile load that contains one of your pages? currently [this one](https://raw.githubusercontent.com/tlienart/FranklinParser.jl/main/src/_precompile/expages/real1.md). If you do, apologies in advance, I'll remove it at once (there are other pages I can use e.g. from my docs). 

Thanks!

**Comment by kescobo** [comment]
By all means! I share this stuff so it can be of use - I never quite imagined it would be put to **this** kind of use, but thrilled it can help in any way 😁

My only concern if the code in the notebook is actually being run on build is that one part calls a web API that can get cranky if called too frequently. Usually, a user would set that up with their own email in case it looks like abuse so they can contact the user, but I think the BioServices.jl wrapper might provide it instead. Just don't want them to be on the hook - can that part of the code be removed, or maybe restricted to a few rows of the DataFrame?

But if the code isn't actually being run, all good!

**Comment by kescobo** [comment]
By all means! I share this stuff so it can be of use - I never quite imagined it would be put to **this** kind of use, but thrilled it can help in any way 😁

My only concern if the code in the notebook is actually being run on build is that one part calls a web API that can get cranky if called too frequently. Usually, a user would set that up with their own email in case it looks like abuse so they can contact the user, but I think the BioServices.jl wrapper might provide it instead. Just don't want them to be on the hook - can that part of the code be removed, or maybe restricted to a few rows of the DataFrame?

But if the code isn't actually being run, all good!

**Comment by tlienart** [comment]
Ah no no that wouldn't happen. This is just the parsing (forming of blocks that have to be resolved), it's even a separate repo (FranklinParser)

Ok thanks a lot then!!
